import Phaser from 'phaser';
import { GAME_WIDTH, GAME_HEIGHT, PALETTE, BRAND } from '../config';

// Loads all art: the procedural room surfaces (exact canon geometry), the
// Higgsfield character/furniture sprites, and the city backdrop.
export class PreloadScene extends Phaser.Scene {
  constructor() {
    super('Preload');
  }

  preload(): void {
    this.load.setBaseURL(import.meta.env.BASE_URL);

    // Room surfaces (@2x, generated by Tools/build_room_art.py)
    this.load.image('floor_a', 'art/room/floor_01_a.png');
    this.load.image('wall', 'art/room/wall_01.png');
    this.load.image('sidewalk', 'art/room/sidewalk.png');
    this.load.image('asphalt', 'art/room/asphalt.png');
    this.load.image('grass', 'art/room/grass.png');
    this.load.image('road_stripe', 'art/room/road_stripe.png');
    this.load.image('wall_door', 'art/room/wall_door.png');
    this.load.image('door_overlay', 'art/room/door_overlay.png');
    this.load.image('corner_seam', 'art/room/corner_seam.png');
    this.load.image('ao_strip', 'art/room/ao_strip.png');
    for (const d of ['stain', 'slime', 'rat', 'boards', 'drip']) {
      this.load.image(`decal_${d}`, `art/room/decal_${d}.png`);
    }

    // Characters (cutout-puppet parts, spec 92 §5)
    for (const c of ['zw', 'cu', 'cw', 'cs']) {
      for (const part of ['head', 'torso', 'armL', 'armR', 'legL', 'legR']) {
        this.load.image(`pp_${c}_${part}`, `art/puppets/${c}_${part}.png`);
      }
    }

    // Furniture sprites
    this.load.image('stove', 'art/stove.png');
    this.load.image('table', 'art/table.png');
    this.load.image('chair', 'art/chair.png');
    this.load.image('counter', 'art/counter.png');
    this.load.image('sink', 'art/sink.png');
    this.load.image('fridge', 'art/fridge.png');

    this.buildProgressBar();
  }

  private buildProgressBar(): void {
    const cx = GAME_WIDTH / 2;
    const cy = GAME_HEIGHT / 2;
    const FONT = "'Trebuchet MS', Verdana, sans-serif";
    this.add.rectangle(0, 0, GAME_WIDTH, GAME_HEIGHT, 0xfaf3e0).setOrigin(0);
    this.add
      .text(cx, cy - 44, BRAND.name.toUpperCase(), {
        fontFamily: FONT,
        fontSize: '34px',
        color: '#5cb544',
        fontStyle: 'bold',
      })
      .setOrigin(0.5)
      .setStroke('#3a2c1c', 6);
    this.add
      .text(cx, cy - 12, 'the service is to die for', {
        fontFamily: FONT,
        fontSize: '13px',
        color: '#8a7a62',
        fontStyle: 'bold italic',
      })
      .setOrigin(0.5);
    this.add.rectangle(cx, cy + 14, 320, 16, 0xffffff).setStrokeStyle(2, PALETTE.panelEdge);
    const fill = this.add.rectangle(cx - 158, cy + 14, 0, 12, PALETTE.toxic).setOrigin(0, 0.5);
    this.load.on('progress', (p: number) => {
      fill.width = 316 * p;
    });
  }

  create(): void {
    const splash = document.getElementById('boot-splash');
    if (splash) {
      splash.style.opacity = '0';
      setTimeout(() => splash.remove(), 420);
    }
    this.scene.start('Cafe');
  }
}
