import Phaser from 'phaser';
import { GAME_WIDTH, GAME_HEIGHT, PALETTE, BRAND } from '../config';

// Loads all art: the procedural room surfaces (exact canon geometry), the
// Higgsfield character/furniture sprites, and the city backdrop.
export class PreloadScene extends Phaser.Scene {
  constructor() {
    super('Preload');
  }

  preload(): void {
    this.load.setBaseURL(import.meta.env.BASE_URL);

    // Room surfaces (@2x, generated by Tools/build_room_art.py)
    this.load.image('floor_a', 'art/room/floor_01_a.png');
    this.load.image('floor_b', 'art/room/floor_01_b.png');
    this.load.image('wall', 'art/room/wall_01.png');
    this.load.image('door_mat', 'art/room/door_mat.png');
    this.load.image('sidewalk', 'art/room/sidewalk.png');
    this.load.image('asphalt', 'art/room/asphalt.png');

    // World & characters
    this.load.image('city_bg', 'art/city_bg.jpg');
    this.load.image('zombie_waiter', 'art/zombie_waiter.png');
    this.load.image('customer', 'art/customer.png');

    // Furniture sprites
    this.load.image('stove', 'art/stove.png');
    this.load.image('table', 'art/table.png');
    this.load.image('chair', 'art/chair.png');
    this.load.image('counter', 'art/counter.png');
    this.load.image('sink', 'art/sink.png');

    this.buildProgressBar();
  }

  private buildProgressBar(): void {
    const cx = GAME_WIDTH / 2;
    const cy = GAME_HEIGHT / 2;
    this.add.rectangle(0, 0, GAME_WIDTH, GAME_HEIGHT, PALETTE.bgTop).setOrigin(0);
    this.add
      .text(cx, cy - 44, BRAND.name.toUpperCase(), {
        fontFamily: 'monospace',
        fontSize: '30px',
        color: '#7ee081',
        fontStyle: 'bold',
      })
      .setOrigin(0.5);
    this.add
      .text(cx, cy - 16, 'the service is to die for', {
        fontFamily: 'monospace',
        fontSize: '12px',
        color: '#8891a4',
      })
      .setOrigin(0.5);
    this.add.rectangle(cx, cy + 10, 320, 16, PALETTE.panel).setStrokeStyle(1, PALETTE.panelEdge);
    const fill = this.add.rectangle(cx - 158, cy + 10, 0, 12, PALETTE.toxic).setOrigin(0, 0.5);
    this.load.on('progress', (p: number) => {
      fill.width = 316 * p;
    });
  }

  create(): void {
    const splash = document.getElementById('boot-splash');
    if (splash) {
      splash.style.opacity = '0';
      setTimeout(() => splash.remove(), 420);
    }
    this.scene.start('Cafe');
  }
}
